name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            python3-pip \
            build-setup \
            git \
            python3-setuptools \
            python3-wheel \
            libltdl-dev \
            libffi-dev \
            libssl-dev \
            zlib1g-dev \
            openjdk-17-jdk \
            autoconf \
            libtool \
            pkg-config \
            libncurses5:i386 \
            libstdc++6:i386 \
            zlib1g:i386
        pip install --upgrade pip
        pip install buildozer cython==0.29.36

    - name: Build with Buildozer
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
